### ISSUE TITLE
[Bug]: Not working anymore on FireFox

### ISSUE THREAD

**Issue by Weetabeex** [dbeck121/CPI-Helper-Chrome-Extension#236] opened 2024-11-12 02:27 UTC
**Describe the bug**
The 5 sections are visible on the screen (Logs / Trace / Messages / Info / Plugins) but nothing happens or I have eror messages when I click on them

**To Reproduce**
1. Go to any flow main screen
2. Click on one of the 5 buttons (ex: logs)
3. Nothing or a red error message

**Expected behavior**
Clicking on ony of the 5 buttons should trigger an action

**Screenshots**

![image](https://github.com/user-attachments/assets/9f11032d-6eae-46b2-8a30-99854525fa03)

**Version**
3.16.0

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 132.0.1 (64-bit)

**Comment by dbeck121** [comment] 2024-11-12 15:25
@Weetabeex 
Thanks for opening this issue.

I checked and I can reproduce the bug. Let me find the root cause and I will come back to you.

**Comment by dbeck121** [comment] 2024-11-12 15:56
@Weetabeex problem found. Will be fixed in next version. Thanks for the issue.

**Comment by dbeck121** [comment] 2024-11-14 15:00
@Weetabeex I pushed 3.17.0 to Firefox store. This might eliminate the problem.

**Comment by Weetabeex** [comment] 2024-11-14 21:31
Working fine. Thanks Beckbaueur, you saved my week

**Closed** 2024-11-14 21:31 UTC
Labels: bug
